JACCARD_MAIN=src/main.cpp
JACCARD_TARGET=jacc.out
JACCARD_TARGET_BST_PER_THREAD=jacc_bpt.out

TARGETS=$(JACCARD_TARGET) $(JACCARD_TARGET_BST_PER_THREAD)

CXX=g++
CXX_FLAGS= -g -Wno-narrowing -lgomp -fopenmp
POP_FLAGS= -lpoplar -lpoputil

MKDIR=mkdir -p
EXECS_LOC=execs

all: dir $(TARGETS)
dir:
	$(MKDIR) $(EXECS_LOC)

$(JACCARD_TARGET):
	$(CXX) $(CXX_FLAGS) $(JACCARD_MAIN) $(POP_FLAGS) -o $(EXECS_LOC)/$@

$(JACCARD_TARGET_BST_PER_THREAD):
	$(CXX) $(CXX_FLAGS) $(JACCARD_MAIN) $(POP_FLAGS) -o $(EXECS_LOC)/$@ -DBST_PER_THREAD

.PHONY: clean
clean:
	@rm -rfv $(EXECS_LOC)/$(JACCARD_TARGET) $(EXECS_LOC)/$(JACCARD_TARGET_BST_PER_THREAD)
